docker:
  generator: github-1
  packages:
    - docker:
        github:
          user: moby
          repo: moby
          query: releases
    - docker-cli:
        github:
          user: docker
          repo: cli
          query: tags
    - docker-compose:
        github:
          user: docker
          repo: compose
          query: releases
    - docker-buildx:
        github:
          user: docker
          repo: buildx
          query: releases
